name: build and push an image to dockerhub
on: #what you want to build on 
  push: #push from where
    branch:
      - main 
#create the env we want to deploy to if it was AWS it would here any env/cloud
env:
  IMAGE_NAME: latest
  DOCKERHUB_REPOSITORY: michie0122/build_image #copy the repo and put it here
jobs: #job to be on an image
  build:
    runs-on: ubuntu-latest #job to run on
    steps: 
      - name:  checkout code #checking out the code from github actions
        uses:  actions/checkout@v2
      - name:  login dockerhub #logging into dockerhub
        uses:  docker/login-action@v1
        with:  
          username: ${{secrets.DOCKERHUB_USERNAME}} #secrets coming form dockerhub/ your credentials
          password: ${{secrets.DOCKERHUB_TOKEN}} #username and token are your variables
      - name: build the docker image #build the docker image
        run: docker build -t  $IMAGE_NAME #command to build an image
      - name: tag the docker image #to run the image you tag the image
        run: docker tag $IMAGE_NAME DOCKERHUB_REPOSITORY:$IMAGE_NAME #code to tag an image AND WHERE YOU ARE TAGGING IT TOO
      - name: push to dockerhub #push to docker hub
        run: docker push DOCKERHUB_REPOSITORY:$IMAGE_NAME




